#!/bin/bash
#
# sublime-anywhere - use Sublime whenever, wherever
# Author: Artur Rosa
# Homepage: https://www.github.com/rossinek/sublime-anywhere
# Strongly inspired by cknadler/vim-anywhere
#
# Uninstalls sublime-anywhere

set -e

###
# opts
###

while getopts ":v" opt; do
  case "$opt" in
    v) set -x ;;
    \?) echo "Invalid option: -$OPTARG" >&2 ;;
  esac
done

###
# defs
###

SAH_PATH=$HOME/.sublime-anywhere
DOC_PATH=/tmp/sublime-anywhere

###
# uninstall
###

rm -rf $SAH_PATH $DOC_PATH

# OSX uninstall
if [[ $OSTYPE == "darwin"* ]]; then
  rm -rf $HOME/Library/Services/SublimeAnywhere.workflow
fi

echo "sublime-anywhere has been successfully uninstalled!"
echo 'Bye.'
